// Auto-generated by scripts/files.js
export const portfolioFiles = [
  "/portfolio/quick-view/biteslice.png",
  "/portfolio/quick-view/cv-electric.png",
  "/portfolio/quick-view/ecolane.png",
  "/portfolio/quick-view/insureonline.png",
  "/portfolio/quick-view/jack-henry.png",
  "/portfolio/quick-view/justworks.png",
  "/portfolio/quick-view/santa-fe-packing.png",
  "/portfolio/quick-view/scm-globe.png",
  "/portfolio/quick-view/study-soup.png",
  "/portfolio/quick-view/superfile.png",
  "/portfolio/quick-view/zooth.png"
];
