// Auto-generated by scripts/files.js
export const portfolioFiles = [
  "/portfolio/quick-view/1-superfile.png",
  "/portfolio/quick-view/2-cv-electric.png",
  "/portfolio/quick-view/3-zooth.png",
  "/portfolio/quick-view/4-santa-fe-packing.png",
  "/portfolio/quick-view/biteslice.png",
  "/portfolio/quick-view/ecolane.png",
  "/portfolio/quick-view/insureonline.png",
  "/portfolio/quick-view/jack-henry.png",
  "/portfolio/quick-view/justworks.png",
  "/portfolio/quick-view/scm-globe.png",
  "/portfolio/quick-view/study-soup.png"
];
