const fs = require('fs');
const path = require('path');

const portfolioDir = path.join(__dirname, '../public/portfolio/quick-view');
const outputFile = path.join(__dirname, '../lib/portfolio.js');

// Read file names and prepend "/portfolio/" to each
const files = fs.readdirSync(portfolioDir)
  .filter(file => fs.statSync(path.join(portfolioDir, file)).isFile())
  .map(file => `/portfolio/quick-view/${file}`);

// Write to output
const fileContent = `// Auto-generated by scripts/files.js
export const portfolioFiles = ${JSON.stringify(files, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent);

console.log(`✅ Wrote ${files.length} file(s) to lib/portfolio.js`);
